### ISSUE TITLE
Volumes

### ISSUE THREAD

**Issue by Happyfeet01** [gutmensch/docker-dmarc-report#11]
Hello,

Possible that an volume is missing in the docker-compose file?

After an restart oder down & up no reports available.

**Comment by Happyfeet01** [comment]
volumes:

      - ./data/db:/var/lib/mysql

**Comment by gutmensch** [comment]
Hey @Happyfeet01 , you are correct, the docker compose example is not complete without the volume definition. Personally I didn't use that approach, because I have MySQL running separately anyway. Would appreciate if you create a PR for a working  example, happy to merge it then! Cheers, Robert

**Comment by Happyfeet01** [comment]
closed with https://github.com/gutmensch/docker-dmarc-report/pull/12

**Comment by Happyfeet01** [comment]
> 
> 
> Hey @Happyfeet01 , you are correct, the docker compose example is not complete without the volume definition. Personally I didn't use that approach, because I have MySQL running separately anyway. Would appreciate if you create a PR for a working example, happy to merge it then! Cheers, Robert

Made an PR :-)
