### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by bsmout** [gutmensch/docker-dmarc-report#15]
I'm getting the following errors when running the docker-compose as specified:

On the webpage: 

Warning: Undefined variable $domains in /var/www/viewer/dmarcts-report-viewer.php on line 315

Warning: Undefined variable $orgs in /var/www/viewer/dmarcts-report-viewer.php on line 316

Warning: Undefined variable $periods in /var/www/viewer/dmarcts-report-viewer.php on line 317

Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/viewer/dmarcts-report-viewer.php:125 Stack trace: #0 /var/www/viewer/dmarcts-report-viewer.php(317): html() #1 {main} thrown in /var/www/viewer/dmarcts-report-viewer.php on line 125

**Comment by bsmout** [comment]
This is the same issue as #9 which looks is

**Comment by bsmout** [comment]
Not fixed in latest but fixed in 1.1

**Comment by gutmensch** [comment]
@bsmout Good catch, thanks for bringing it up! Just pushed 1.1 as latest now. I'll try to improve the build pipeline with stable upstream versions of the parser and the viewer, when I have a new CI setup.
