### ISSUE TITLE
php errors when no data (Warning: Undefined variable)

### ISSUE THREAD

**Issue by Pjort** [gutmensch/docker-dmarc-report#17]
If you start up a new container and DB it will show following error:

Warning: Undefined variable $domains in /var/www/viewer/dmarcts-report-viewer.php on line 315

Warning: Undefined variable $orgs in /var/www/viewer/dmarcts-report-viewer.php on line 316

Warning: Undefined variable $periods in /var/www/viewer/dmarcts-report-viewer.php on line 317

**Comment by gutmensch** [comment]
This is a bug of the upstream viewer [source](https://github.com/techsneeze/dmarcts-report-viewer/), see some more explanations in #16 e.g.

Writing a patch in this repo does not sound like a good idea.

**Comment by olenoerby** [comment]
The container does indeed create the data on first successful report arrival on the email account, but here is the database structure, if you wish to put them in the MySQL database.

`
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `report` (
  `serial` int(10) UNSIGNED NOT NULL,
  `mindate` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `maxdate` timestamp NULL DEFAULT NULL,
  `domain` varchar(255) COLLATE utf8_bin NOT NULL,
  `org` varchar(255) COLLATE utf8_bin NOT NULL,
  `reportid` varchar(255) COLLATE utf8_bin NOT NULL,
  `email` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `extra_contact_info` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `policy_adkim` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `policy_aspf` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `policy_p` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `policy_sp` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `policy_pct` tinyint(3) UNSIGNED DEFAULT NULL,
  `raw_xml` mediumtext COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPRESSED;

CREATE TABLE `rptrecord` (
  `id` int(10) UNSIGNED NOT NULL,
  `serial` int(10) UNSIGNED NOT NULL,
  `ip` int(10) UNSIGNED DEFAULT NULL,
  `ip6` binary(16) DEFAULT NULL,
  `rcount` int(10) UNSIGNED NOT NULL,
  `disposition` enum('none','quarantine','reject','unknown') COLLATE utf8_bin DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `dkimdomain` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `dkimresult` enum('none','pass','fail','neutral','policy','temperror','permerror','unknown') COLLATE utf8_bin DEFAULT NULL,
  `spfdomain` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `spfresult` enum('none','neutral','pass','fail','softfail','temperror','permerror','unknown') COLLATE utf8_bin DEFAULT NULL,
  `spf_align` enum('fail','pass','unknown') COLLATE utf8_bin NOT NULL,
  `dkim_align` enum('fail','pass','unknown') COLLATE utf8_bin NOT NULL,
  `identifier_hfrom` varchar(255) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


ALTER TABLE `report`
  ADD PRIMARY KEY (`serial`),
  ADD UNIQUE KEY `domain` (`domain`,`reportid`);

ALTER TABLE `rptrecord`
  ADD PRIMARY KEY (`id`),
  ADD KEY `serial` (`serial`,`ip`),
  ADD KEY `serial6` (`serial`,`ip6`);


ALTER TABLE `report`
  MODIFY `serial` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `rptrecord`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

`

**Comment by gutmensch** [comment]
should be fixed with latest release 1.3 and db bootstrapping by parser during startup
