### ISSUE TITLE
Deploying the docker container deploys with an error that the database table does not exist.

### ISSUE THREAD

**Issue by okoeroo** [gutmensch/docker-dmarc-report#19]
Directly after deployment:

Query failed: Table 'dmarc_report.report' doesn't exist (Error #1146)

And... I can't find the SQL that generate the tables for force it.

**Comment by gene1wood** [comment]
I think the tool provisions the tables when it first receives a DMARC report. Have you waited until a report came in and does it still show the error?

**Comment by gutmensch** [comment]
should be fixed with latest release 1.3, which runs the db creation from parser during initial startup.
