### ISSUE TITLE
Less dirty hack

### ISSUE THREAD

**Issue by smpita** [gutmensch/docker-dmarc-report#3]
In `entrypoint.sh`, you use a combination of `find` and `sed` to replace variables in `dmarcts-report-viewer-config.php` and `dmarcts-report-parser.conf`. That's unnecessary because both of these files are parsed by binaries that can directly read the environment.

Try these:
`$dbname = $ENV{'REPORT_DB_NAME'};` instead of  `$dbname = '$$_REPORT_DB_NAME_$$';` in `dmarcts-report-parser.conf` 
`$dbname=getenv('REPORT_DB_NAME')` instead of `$dbname='$$_REPORT_DB_NAME_$$';` in `dmarcts-report-viewer-config.php`

**Comment by gutmensch** [comment]
Hey @smpita , you're absolutely right. Care to provide a PR for that change? If not, I'll have a look soonish. Thanks for reporting!
