### ISSUE TITLE
host name reverse lookup isn't working

### ISSUE THREAD

**Issue by k3it** [gutmensch/docker-dmarc-report#30]
The web reports have IP addresses in the Host Name column despite

`$default_hostlookup = 1;  # 1=on 0=off (on is old behaviour )`

setting in `/var/www/viewer/dmarcts-report-viewer-config.php `

Any advice on how to enable name resolution?

![image](https://user-images.githubusercontent.com/9923389/209056888-54913b7c-a913-410c-9cef-50f48d379c29.png)

**Comment by gutmensch** [comment]
Hey @k3it , hm strange. It works for me as expected (see screenshots). The php script seems to call the standard C library function `gethostbyaddr` [here](https://github.com/techsneeze/dmarcts-report-viewer/blob/5901db238cd905f2313caf6379cfd8c00d38cb45/dmarcts-report-viewer-report-data.php#L156) and the address in your report has a PTR, so maybe try for debugging
```
$ docker exec -ti dmarc-report bash
# apk add -U bind-tools
# host 192.40.173.187
187.173.40.192.in-addr.arpa domain name pointer mailer187.gate173.rs.smtp.com.
```
It might be that your docker engine has specific DNS settings, which would cause this behaviour.

<img width="591" alt="hostname_lookup2" src="https://user-images.githubusercontent.com/585578/210974231-77cdfb08-18af-4ddc-9f89-cd693e3b5ab8.png">
<img width="627" alt="hostname_lookup1" src="https://user-images.githubusercontent.com/585578/210974238-3e948cef-1331-4886-80b7-55aa25bc9ed0.png">

**Comment by k3it** [comment]
@gutmensch  you are right, the reverse lookups are not working with the docker internal resolver pointing to 127.0.0.11, while the forward lookups are fine.   this is a container running in WSL2 ubuntu.   any new container has the same problem, definitely unrelated to anything in your code. Thanks for your help!
