### ISSUE TITLE
Compose sample missing storage for DB

### ISSUE THREAD

**Issue by Codelica** [gutmensch/docker-dmarc-report#36]
Hello...  thanks for the project. 👍  Just a quick note that the compose sample seems to be missing a storage volume to persist the stats data in Maria.  

```yaml
    volumes:
      - ./dmarc-report-db:/var/lib/mysql
```

Thanks again.

**Comment by gutmensch** [comment]
Hey @Codelica , good catch, thank you! Feel free to PR a change, happy to merge. :-) I'm not using compose myself, so I appreciate support keeping this close to reality.

**Comment by gutmensch** [comment]
Fixed with https://github.com/gutmensch/docker-dmarc-report/commit/e7c55a0d2cd42cfb63e03c563f02c56054c81ea4
