### ISSUE TITLE
Enhancement: Use secrets

### ISSUE THREAD

**Issue by awebeer256** [gutmensch/docker-dmarc-report#40]
It's not great to include your email password in your `docker-compose.yml`.

After a bit of reading, I wasn't able to find a way to pass a secret as an environment variable (as opposed to as a file) to just one container in a composed service.

**Comment by gutmensch** [comment]
@awebeer256 Sorry, but you are talking about something here that is not related to this image. docker-compose is one example to run a container, but you can use better ways/secure ways like secret injection in your scheduler, etc. pp - but it's not a job of this container image to do that or describe this for you in great detail. There is information in the Internet how to run your scheduled workloads securely and properly.
