### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by majoragee** [gutmensch/docker-dmarc-report#46]
I'm trying to setup docker-dmarc-report for the first time using the docker-compose.yml from the readme and the dmarc-report container will not start.  I am getting absolutely nothing in the logs other than from mariadb, which starts successfully.  A `docker compose ps` shows the container as `health: starting` for a minute or two before it finally does completely.  At no point is the application connectable in the browser.

I'm not sure how to troubleshoot further without any logs.  Thank you!

**Comment by gutmensch** [comment]
@majoragee Please provide the output of 
```
docker ps
```
and
```
curl localhost:80 -v -s -o /dev/null
```
Cheers

**Comment by majoragee** [comment]
I figured out the issue.  I usually use IMAPS and forgot that the IMAP port for STARTTLS was blocked by the firewall.  I switched the port and encryption method and I'm up and running.  If there's any issue here, it's that it fails silently.

Thanks again for your work!
