### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by ghnp5** [gutmensch/docker-dmarc-report#47]
Hey!

I'd like to report this PHP error that appears in the docker logs:

> NOTICE: PHP message: PHP Deprecated:  Optional parameter $option declared before required parameter $var is implicitly treated as a required parameter in /var/www/viewer/dmarcts-report-viewer-options.php on line 216  
 
> 2024/01/28 10:14:26 [error] 99#99: *39 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Optional parameter $option declared before required parameter $var is implicitly treated as a required parameter in /var/www/viewer/dmarcts-report-viewer-options.php on line 216" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /dmarcts-report-viewer-options.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "127.0.0.1:9012", referrer: "https://xxxxxx/"

**Comment by gutmensch** [comment]
Please report this here https://github.com/techsneeze/dmarcts-report-viewer/blob/master/dmarcts-report-viewer-options.php#L216 - thanks!

**Comment by ghnp5** [comment]
Thanks. Done - https://github.com/techsneeze/dmarcts-report-viewer/issues/93
