### ISSUE TITLE
[BUG] after last Update

### ISSUE THREAD

**Issue by n3roGit** [gutmensch/docker-dmarc-report#53]
The container has unfortunately stopped working since the last update :(

```
CRIT: Dmarc reports could not be parsed. Check your IMAP and MYSQL Settings.
DEBUG: Parsing failed with the following output:
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at (eval 117) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Pg, Proxy, Sponge.
 at /usr/bin/dmarcts-report-parser.pl line 273.
```

**Comment by gitviola** [comment]
Same here

**Comment by gutmensch** [comment]
Checking what happened to the perl module - meh, seems upstream underlaying image update causing some trouble here 
```
#8 812.4 DBD::mysql requires MySQL 8.x for building. Version reported by mysql_config --version: 10.5.5 at Makefile.PL line 451, <PIPE> line 3.
#8 812.4 Warning: No success on command[/usr/bin/perl Makefile.PL]
#8 812.4   DVEEDEN/DBD-mysql-5.003.tar.gz
#8 812.4   /usr/bin/perl Makefile.PL -- NOT OK
```
looks like pinning to DBD::mysql version 4.052 (which doesn't fail against MariaDB 10.x) should help here, will give this a try

**Comment by gutmensch** [comment]
@n3roGit Could you maybe help me out and try ` gutmensch/dmarc-report:1.4.4-test` and report if the problem is fixed and everything works as expected? I'm lacking an own e2e testing possibility atm. MySQL module should be back in this build, after the pinning in the related PR.

**Comment by n3roGit** [comment]
Its the same:

`      
CRIT: Dmarc reports could not be parsed. Check your IMAP and MYSQL Settings.
DEBUG: Parsing failed with the following output:
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at (eval 117) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Pg, Proxy, Sponge.
 at /usr/bin/dmarcts-report-parser.pl line 273.

      `


![image](https://github.com/gutmensch/docker-dmarc-report/assets/8565847/e14c051f-f0df-4c38-85db-fdccc2f9cd2d)

**Comment by gutmensch** [comment]
@n3roGit thanks heaps for the support :medal_military:  another try please with `gutmensch/dmarc-report:1.4.4-test2`

**Comment by n3roGit** [comment]
![image](https://github.com/gutmensch/docker-dmarc-report/assets/8565847/8f0d4881-62f3-44b3-8fc8-e8b56c5e27e9)
![image](https://github.com/gutmensch/docker-dmarc-report/assets/8565847/5338421a-f84d-47fc-b1dc-937832cb5a43)


You are welcome :)

The Container is starting for a loong loong time without logging now.

**Comment by n3roGit** [comment]
![image](https://github.com/gutmensch/docker-dmarc-report/assets/8565847/33667fc9-212d-43b5-8238-bbf5730bd835)
@gutmensch ITS WORKING!!! After ~10 Minutes of starting

**Comment by gutmensch** [comment]
@n3roGit Ok the starting delay is a bit odd, the health check should be fine after 1 min
```
HEALTHCHECK --interval=1m --timeout=3s CMD curl --silent --fail http://127.0.0.1:80/fpm-ping
```
but I think we are good for now then (while I can implement some own e2e here). Releasing official version 1.4.4 then, thanks again a lot for your support!
