### ISSUE TITLE
imap read folder not defined

### ISSUE THREAD

**Issue by Project23D** [gutmensch/docker-dmarc-report#55]
docker-compose.yml
except:

- "PARSER_IMAP_SERVER=mail.***.io"
      - "PARSER_IMAP_PORT=143"
      - "PARSER_IMAP_USER=*@***.io"
      - "PARSER_IMAP_PASS=endsin12"
      - "PARSER_IMAP_READ_FOLDER=Inbox"
      - "PARSER_IMAP_MOVE_FOLDER=processed"
      - "PARSER_IMAP_MOVE_FOLDER_ERR=error"
      

root@vault:~/dmarc-report# docker run -e docker-compose.yml -ti gutmensch/dmarc-report
CRIT: Dmarc reports could not be parsed. Check your IMAP and MYSQL Settings.
DEBUG: Parsing failed with the following output: 
dmarcts-report-parser.pl: $imapreadfolder not defined. Check config file at /usr/bin/dmarcts-report-parser.pl line 201.

**Comment by gutmensch** [comment]
@Project23D For docker-compose format you need actually `docker-compose` and not only `docker` e.g. from here https://docs.docker.com/compose/install/standalone/

For your command you would need to change this to something like
```bash
docker run -e PARSER_IMAP_SERVER=example.com -e PARSER_IMAP_READ_FOLDER=Inbox -e ... -ti gutmensch/dmarc-report
```

**Comment by gutmensch** [comment]
The docker compose format in the README is just _provided as example_ - if you don't use compose and/or use other container "wrappers" you need to figure out the correct application of environment variables yourself.
